
### get AM_SLA
POST http://localhost:4004/srv/updateSLA
Content-Type: application/json
# Authorization: Basic daniele.veron@lab2dev.com Dani@lab

{
    "payload": {
        "sequencial": "0050568C60C01EEC96BF274B5218CD27",
        "numero_ov": 431150461,
        "dt_st_atual": "2021-08-30",
        "hr_st_atual": "08:53:08",
        "tipo_ov": "ZBRU",
        "status": "820",
        "org_vendas": "5100",
        "cnl_distr": "40",
        "escr_vdas": "5184",
        "eqp_vdas": "1Z5",
        "data_sla": "2021-08-30",
        "hra_sla": "11:00:00",
        "nivel": 1,
        "usuario": "93097166",
        "btp": true,
        "expresso": false,
        "dta_slalocal": "2021-08-30",
        "hra_slalocal": "11:00:00",
        "email": "rpaulo@minsait.com",
        "data_encerramento": "2022-03-22",
        "hra_encerramento": "17:20:00"
    }
}

### get getRelatorioSintetic
GET http://localhost:4004/srv/getRelatorioSintetic(from='2022-01-01T10:55:00Z',range=20)
Content-Type: application/json
# Authorization: Basic daniele.veron@lab2dev.com Dani@lab

{
    "payload": {        
        "numero_ov": 63532200,        
    }
}

### Post AM_JOB
POST http://localhost:4004/srv/AM_JOB
Content-Type: application/json
# Authorization: Basic daniele.veron@lab2dev.com Dani@lab

{
    "sequencial":"2",
    "hora" : "11:00:00",
    "email" : "kaio.mattos200@gmail.com"
}