namespace alarmmonitt2.db;
context ALARMMONIT { @cds.persistence.exists entity AM_EMAILXFONENUMBER { key email : String(100) not null;
fonenumber : Integer;
};
@cds.persistence.exists entity AM_JOB { key sequencial : String(32) not null;
hora : Time;
email : String(100);
};
@cds.persistence.exists entity AM_SLA { key numero_ov : Integer not null;
key sequencial : String(32) not null;
dt_st_atual : Date not null;
hr_st_atual : Time not null;
tipo_ov : String(50);
status : Integer;
org_vendas : String(4);
cnl_distr : String(2);
escr_vdas : String(4);
eqp_vdas : String(50);
data_sla : Date;
hra_sla : Time;
nivel : Integer;
usuario : String(50);
btp : Boolean;
expresso : Boolean;
dta_slalocal : Date;
hra_slalocal : Time;
email : String(500);
data_encerramento : Date;
hra_encerramento : Time;
};
@cds.persistence.exists entity AM_SLA_LEGADO { messageid : String(50);
systemid : String(20);
usuario : String(50);
key numero_ov : Integer not null;
key sequencial : String(32) not null;
status : Integer;
distchannel : String(4);
dt_st_atual : Date not null;
hr_st_atual : Time not null;
data_sla : Date;
hra_sla : Time;
sent2ecc : String(1);
};
@cds.persistence.exists entity AM_STATUS { key id_sistema : String(50) not null;
key id_organizacional : String(50) not null;
key status : Integer not null;
key expresso : Boolean not null;
key nivel : Integer not null;
email : String(500);
};
@cds.persistence.exists entity AM_STATUSTXT { key systemid : String(20) not null;
key status : Integer not null;
descricao : String(100);
};
@cds.persistence.exists entity AM_VENDAS { key tipo_documento_vendas : String(50) not null;
key canal_distribuicao : Integer not null;
key nivel : Integer not null;
key status : Integer not null;
key expresso : Boolean not null;
sla : String(8);
hrs_uteis : Boolean;
};
}